version: '3.9'

services:
  ergopay:
    container_name: ergopay
    env_file: ${ENV_FILE}
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./app:/app
    ports:
      - 7000:7000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 90s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    working_dir: /app
    command: tail /dev/null -f
    # command: uvicorn main:app --reload --workers 4 --reload-dir /app --host 0.0.0.0 --port ${API_PORT}
    networks:
      - ergopad-data_net
      - ergopad-node_net

networks:
  ergopad-data_net:
    external: true
  ergopad-node_net:
    external: true
